### PR TITLE
Fixed job ID for encrypt's progress event

### PR DESCRIPTION
**Pull request by Wassup789**
Currently, the job id emitted by `encryptStream`'s call to `emitProgress` returns a job id of `"[encrypted file]"`.
I updated the value to the corresponding job id since otherwise there's no way to identify which encrypt job a progress event came from.

### CODE REVIEW

**Comment by smulikHakipod** [comment]
@eligrey any news? why not? this seems like a really bad bug

**Comment by eligrey** [comment]
> > I'll be checking out this PR later today

**Comment by eligrey** [comment]
Sorry about the delay. I'll be getting to triage this issue later this week hopefully.

**Comment by gadirotenberg** [comment]
> Sorry about the delay. I'll be getting to triage this issue later this week hopefully.

Any news on this issue? Is this repo still maintained?

**Comment by michaelfarrell76** [comment]
@gadirotenberg apologies about the delay this fell through the cracks. we'll get this merged

**Comment by eligrey** [comment]
sorry about that. this issue fell through the cracks

**Pull request merged**
