### PR TITLE
Adds declaration map in build

### PR DESCRIPTION
**Pull request by michaelfarrell76**
Types were removed in recent webpack refactor

### CODE REVIEW

**Comment by bencmbrook** [comment]
Seems this is duping everything 
Screen Shot 2020-05-13 at 11 59 31 AM

**Comment by michaelfarrell76** [comment]
It doesn't matter, we only include the penumbra.js and penumbra.work.js file in our webpack builds: https://github.com/transcend-io/main/blob/37b7dec6e86c855b59a4136b5879fc4af08ec253/packages/admin-dashboard/webpack/webpack.base.babel.js#L157

**Comment by michaelfarrell76** [comment]
im honestly just looking for a quick fix here

**Comment by bencmbrook** [comment]
Can you import Penumbra locally for the quick fix then? Would rather not put this on `master` and publish to NPM.

**Pull request merged**
