### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by eligrey**
## Related Issues

- _[none]_

## Public Changelog

_[none]_

## Security Implications

_[none]_

### CODE REVIEW

**Review by michaelfarrell76 — COMMENTED** [review]
can we use ` yarn upgrade-interactive` to update the package.json versions too?

**Comment by eligrey** [comment]
strangely enough, this was the output from upgrade-interactive. I think I may need to manually update versions in package.json here

**Comment by michaelfarrell76** [comment]
weird, maybe its because this repo isn't pnp'd

**Comment by eligrey** [comment]
picking this back up today

**Pull request closed without merging**
