### PR TITLE
Fetch includes credentials

### PR DESCRIPTION
**Pull request by michaelfarrell76**
penumbra.get includes credentials by default in order to preserve login sessions

### CODE REVIEW

**Comment by michaelfarrell76** [comment]
not sure if credentials should be included by default or we want to expose this out

**Comment by eligrey** [comment]
This is good for now. We will also want to expose this as a configurable property in penumbra.get() eventually.

**Comment by michaelfarrell76** [comment]
TODO need to bubble error back up `penumbra.get({ … }).then((response) => response).catch((err) => ...)` to handle session expiry

**Comment by eligrey** [comment]
I can work on this today if you need help bubbling that error up from the worker.

**Comment by michaelfarrell76** [comment]
that would be awesome. ideally it still works with the API `penumbra.get({ … }).then((response) => response).catch((err) => ...)` and so it would have to emit an error, the main thread would have to detect the error and then re throw it so penumbra.get receieves the error

**Comment by eligrey** [comment]
I added some helper functions and setup for bubbling errors in #84

**Comment by michaelfarrell76** [comment]
we will need to expose fetch options since include credentials is now allowed when access control origin is * (as in the case of privacy centers)

**Comment by eligrey** [comment]
I'll add credentials to penumbra.get as well as implementing error bubbling to get this PR working today.

**Comment by michaelfarrell76** [comment]
ur the man

**Comment by eligrey** [comment]
Should be fixed now in `eligrey/bubble-bubble-toil-and-trouble`.

**Pull request closed without merging**
