### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by eligrey**
## Related Issues

- _[none]_

## Public Changelog

_[none]_

## Security Implications

_[none]_

### CODE REVIEW

**Review by michaelfarrell76 — APPROVED** [review]
thanks, can we update this in the monorepo and give it a manual test to ensure it still works?

**Comment by eligrey** [comment]
@michaelfarrell76 I've manually tested this PR and I'll update the monorepo after publishing.

**Comment by eligrey** [comment]
I haven't fixed the CI jobs yet so I'll get that done on Monday before merging this.

**Comment by bencmbrook** [comment]
Updating Netlify build image to upgrade Node version (the netlify builds are failing)

**Comment by michaelfarrell76** [comment]
see https://github.com/transcend-io/penumbra/pull/206

**Pull request closed without merging**
